on: [push]

name: CI

jobs:
  build:
    name: srcds_tools
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            "src/target/release/srcds_tools.exe"
